# -*- coding: utf-8 -*-
"""Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156QLxyXLvkF5sik4v_NC8gZh_JEKaUDA
"""

!pip install ultralytics -q
!mkdir -p adas-yolo-detection/data/input

!wget -q -O adas-yolo-detection/data/input/test.jpg https://ultralytics.com/images/bus.jpg

from ultralytics import YOLO
from IPython.display import Image, display
import os, glob

model = YOLO("yolo11n.pt")

results = model.predict(
    source="/content/adas-yolo-detection/data/input/test.jpg",
    conf=0.35,
    save=True,
    project="/content/adas-yolo-detection/data/output",
    name="results",
    exist_ok=True
)

print("Save dir:", results[0].save_dir)
print("Files:", os.listdir(results[0].save_dir))

image_files = glob.glob(str(results[0].save_dir) + "/*.jpg")
display(Image(filename=image_files[0]))

!rm -f /content/adas-yolo-detection/data/input/traffic.mp4

import os
print(os.listdir("/content/runs/detect/predict"))

from google.colab import files
uploaded = files.upload()

import os, shutil

os.makedirs("/content/adas-yolo-detection/data/input", exist_ok=True)

for filename in uploaded.keys():
    video_path = "/content/adas-yolo-detection/data/input/" + filename
    shutil.move(filename, video_path)

print("Video path:", video_path)
print("Size:", os.path.getsize(video_path))

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

video_results = model.predict(
    source=video_path,
    conf=0.35,
    save=True
)

print("Saved in:", video_results[0].save_dir)

from IPython.display import HTML
from base64 import b64encode
import glob


videos = glob.glob("/content/runs/detect/predict/*.avi")

video_path = videos[0]

mp4 = open(video_path, "rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width="700" controls>
  <source src="{data_url}" type="video/mp4">
</video>
""")

import os
print(os.listdir("/content/runs/detect/predict"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from ultralytics import YOLO
# import tempfile
# import cv2
# import os
# import glob
# 
# st.set_page_config(page_title="ADAS YOLO Detection", layout="wide")
# 
# st.title("🚗 ADAS Object Detection using YOLO")
# 
# st.write(
#     """
# Upload an image or video to detect:
# - Cars
# - Pedestrians
# - Trucks
# - Buses
# - Motorcycles
# """
# )
# 
# # Load model
# model = YOLO("yolo11n.pt")
# 
# # Upload file
# uploaded_file = st.file_uploader(
#     "Upload image or video",
#     type=["jpg", "jpeg", "png", "mp4", "avi"]
# )
# 
# # Confidence slider
# conf = st.slider(
#     "Confidence Threshold",
#     min_value=0.1,
#     max_value=0.9,
#     value=0.35,
#     step=0.05
# )
# 
# if uploaded_file is not None:
# 
#     suffix = os.path.splitext(uploaded_file.name)[1]
# 
#     # Save uploaded file temporarily
#     with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
#         tmp.write(uploaded_file.read())
#         input_path = tmp.name
# 
#     # =========================
#     # IMAGE DETECTION
#     # =========================
#     if suffix.lower() in [".jpg", ".jpeg", ".png"]:
# 
#         st.info("Processing image...")
# 
#         results = model.predict(
#             source=input_path,
#             conf=conf
#         )
# 
#         annotated_image = results[0].plot()
# 
#         st.image(
#             annotated_image,
#             caption="Detection Result",
#             channels="BGR",
#             use_container_width=True
#         )
# 
#         st.success("Image processing completed!")
# 
#        # =========================
#     # VIDEO DETECTION
#     # =========================
#     else:
#         st.info("Processing video... Please wait ⏳")
# 
#         cap = cv2.VideoCapture(input_path)
# 
#         if not cap.isOpened():
#             st.error("Error: Could not open video.")
#         else:
#             fps = int(cap.get(cv2.CAP_PROP_FPS))
#             width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
#             height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
# 
#             output_path = "processed_video.mp4"
# 
#             fourcc = cv2.VideoWriter_fourcc(*"mp4v")
#             out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))
# 
#             progress_bar = st.progress(0)
#             total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
#             frame_count = 0
# 
#             while True:
#                 ret, frame = cap.read()
#                 if not ret:
#                     break
# 
#                 results = model.predict(frame, conf=conf)
#                 annotated_frame = results[0].plot()
# 
#                 out.write(annotated_frame)
# 
#                 frame_count += 1
#                 if total_frames > 0:
#                     progress_bar.progress(min(frame_count / total_frames, 1.0))
# 
#             cap.release()
#             out.release()
# 
#             st.success("Video processing completed!")
# 
#             with open(output_path, "rb") as file:
#                 st.download_button(
#                     label="📥 Download Processed Video",
#                     data=file,
#                     file_name="processed_video.mp4",
#                     mime="video/mp4"
#                 )

!pip install streamlit ultralytics opencv-python pyngrok -q

from pyngrok import ngrok

ngrok.kill()
ngrok.set_auth_token("3DPI9vqRElxeONOksdLFD0C2Exf_4P6RmPf4YxM9k8k33CYEB")

!streamlit run app.py --server.port 8501 &>/dev/null &

public_url = ngrok.connect(8501)
print(public_url)



